'use client';

import { useState } from 'react';

interface GameData {
  gameNumber: number;
  points: Array<{
    scorer: string;
    score: string;
    isHandout: boolean;
    servingSide: 'left' | 'right';
    server: string;
  }>;
  winner: string;
  finalScore: string;
  duration: number;
  startTime: Date;
  endTime: Date;
}

interface GameDetailModalProps {
  game: GameData;
  player1: string;
  player2: string;
  isOpen: boolean;
  onClose: () => void;
}

export default function GameDetailModal({ game, player1, player2, isOpen, onClose }: GameDetailModalProps) {
  const [showFullTranscript, setShowFullTranscript] = useState(false);

  if (!isOpen) return null;

  const formatDuration = (seconds: number): string => {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  };

  const formatTime = (date: Date): string => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const printGameTranscript = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Game ${game.gameNumber} Transcript - ${player1} vs ${player2}</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              margin: 20px; 
              line-height: 1.6; 
            }
            .header { 
              text-align: center; 
              border-bottom: 2px solid #333; 
              padding-bottom: 20px; 
              margin-bottom: 30px; 
            }
            .game-summary { 
              background: #f5f5f5; 
              padding: 15px; 
              border-radius: 8px; 
              margin-bottom: 20px; 
            }
            .points-table { 
              width: 100%; 
              border-collapse: collapse; 
              margin-top: 20px; 
            }
            .points-table th, .points-table td { 
              border: 1px solid #ddd; 
              padding: 8px; 
              text-align: center; 
            }
            .points-table th { 
              background-color: #f2f2f2; 
              font-weight: bold; 
            }
            .handout { 
              background-color: #fff3cd; 
            }
            @media print { 
              body { margin: 0; } 
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Squash Game Transcript</h1>
            <h2>Game ${game.gameNumber}: ${player1} vs ${player2}</h2>
          </div>
          
          <div class="game-summary">
            <h3>Game Summary</h3>
            <p><strong>Winner:</strong> ${game.winner}</p>
            <p><strong>Final Score:</strong> ${game.finalScore}</p>
            <p><strong>Duration:</strong> ${formatDuration(game.duration)}</p>
            <p><strong>Start Time:</strong> ${formatTime(game.startTime)}</p>
            <p><strong>End Time:</strong> ${formatTime(game.endTime)}</p>
            <p><strong>Total Points:</strong> ${game.points.length}</p>
            <p><strong>Handouts:</strong> ${game.points.filter(p => p.isHandout).length}</p>
          </div>
          
          <h3>Point-by-Point Breakdown</h3>
          <table class="points-table">
            <thead>
              <tr>
                <th>Point #</th>
                <th>Scorer</th>
                <th>Score</th>
                <th>Server</th>
                <th>Serving Side</th>
                <th>Handout</th>
              </tr>
            </thead>
            <tbody>
              ${game.points.map((point, index) => `
                <tr class="${point.isHandout ? 'handout' : ''}">
                  <td>${index + 1}</td>
                  <td><strong>${point.scorer}</strong></td>
                  <td>${point.score}</td>
                  <td>${point.server}</td>
                  <td>${point.servingSide}</td>
                  <td>${point.isHandout ? '✓' : ''}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          
          <div style="margin-top: 30px; text-align: center; color: #666; font-size: 12px;">
            Generated by Squash Ref Support App
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  const handouts = game.points.filter(p => p.isHandout).length;
  const player1Points = game.points.filter(p => p.scorer === player1).length;
  const player2Points = game.points.filter(p => p.scorer === player2).length;
  
  const servingStats = {
    [player1]: {
      left: game.points.filter(p => p.server === player1 && p.servingSide === 'left').length,
      right: game.points.filter(p => p.server === player1 && p.servingSide === 'right').length,
    },
    [player2]: {
      left: game.points.filter(p => p.server === player2 && p.servingSide === 'left').length,
      right: game.points.filter(p => p.server === player2 && p.servingSide === 'right').length,
    },
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-2xl shadow-xl max-w-6xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-gray-200">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">
              Game {game.gameNumber} Details
            </h2>
            <p className="text-lg text-gray-600">
              {player1} vs {player2}
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={printGameTranscript}
              className="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg font-medium transition-colors"
            >
              📄 Print
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 bg-gray-500 hover:bg-gray-600 text-white rounded-lg font-medium transition-colors"
            >
              ✕ Close
            </button>
          </div>
        </div>

        <div className="p-6">
          {/* Game Summary */}
          <div className="grid lg:grid-cols-4 gap-4 mb-8">
            <div className="bg-green-50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-green-600 mb-1">{game.winner}</div>
              <div className="text-sm text-gray-600">Winner</div>
            </div>
            <div className="bg-blue-50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-blue-600 mb-1">{game.finalScore}</div>
              <div className="text-sm text-gray-600">Final Score</div>
            </div>
            <div className="bg-purple-50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-purple-600 mb-1">{formatDuration(game.duration)}</div>
              <div className="text-sm text-gray-600">Duration</div>
            </div>
            <div className="bg-orange-50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-orange-600 mb-1">{game.points.length}</div>
              <div className="text-sm text-gray-600">Total Points</div>
            </div>
          </div>

          {/* Scoring Rules Info */}
          <div className="bg-blue-50 rounded-lg p-4 mb-8 border-l-4 border-blue-400">
            <div className="flex items-start">
              <div className="text-blue-400 mr-3 mt-0.5">ℹ️</div>
              <div>
                <h4 className="font-medium text-blue-900 mb-1">Squash Scoring Rules</h4>
                <p className="text-sm text-blue-800">
                  Games are played to <strong>11 points</strong> with a <strong>win-by-2 rule</strong>. 
                  If tied at 10-10, play continues until one player leads by 2 points, or until someone reaches <strong>15 points</strong> (maximum).
                </p>
              </div>
            </div>
          </div>

          {/* Detailed Statistics */}
          <div className="grid lg:grid-cols-2 gap-6 mb-8">
            {/* Player Statistics */}
            <div className="bg-gray-50 rounded-lg p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Player Statistics</h3>
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="font-medium text-gray-900">{player1}</span>
                  <span className="text-blue-600 font-bold">{player1Points} points</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="font-medium text-gray-900">{player2}</span>
                  <span className="text-green-600 font-bold">{player2Points} points</span>
                </div>
                <div className="border-t pt-2">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Total Handouts:</span>
                    <span className="font-medium text-gray-900">{handouts}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Serving Statistics */}
            <div className="bg-gray-50 rounded-lg p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Serving Statistics</h3>
              <div className="space-y-4">
                <div>
                  <div className="font-medium text-gray-900 mb-2">{player1}</div>
                  <div className="flex justify-between text-sm text-gray-700">
                    <span>Left side: {servingStats[player1].left}</span>
                    <span>Right side: {servingStats[player1].right}</span>
                  </div>
                </div>
                <div>
                  <div className="font-medium text-gray-900 mb-2">{player2}</div>
                  <div className="flex justify-between text-sm text-gray-700">
                    <span>Left side: {servingStats[player2].left}</span>
                    <span>Right side: {servingStats[player2].right}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Game Timeline */}
          <div className="bg-gray-50 rounded-lg p-6 mb-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Game Timeline</h3>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-gray-600">Start:</span>
                <span className="font-medium text-gray-900 ml-2">{formatTime(game.startTime)}</span>
              </div>
              <div>
                <span className="text-gray-600">End:</span>
                <span className="font-medium text-gray-900 ml-2">{formatTime(game.endTime)}</span>
              </div>
            </div>
          </div>

          {/* Point Progression */}
          <div className="bg-white border border-gray-200 rounded-lg p-6">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold text-gray-900">Point-by-Point Breakdown</h3>
              <button
                onClick={() => setShowFullTranscript(!showFullTranscript)}
                className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
              >
                {showFullTranscript ? 'Show Summary' : 'Show Full Transcript'}
              </button>
            </div>

            {showFullTranscript ? (
              /* Full Table */
              <div className="overflow-x-auto">
                <table className="w-full border-collapse">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="border border-gray-300 px-3 py-2 text-xs font-medium text-gray-700">Point</th>
                      <th className="border border-gray-300 px-3 py-2 text-xs font-medium text-gray-700">Scorer</th>
                      <th className="border border-gray-300 px-3 py-2 text-xs font-medium text-gray-700">Score</th>
                      <th className="border border-gray-300 px-3 py-2 text-xs font-medium text-gray-700">Server</th>
                      <th className="border border-gray-300 px-3 py-2 text-xs font-medium text-gray-700">Side</th>
                      <th className="border border-gray-300 px-3 py-2 text-xs font-medium text-gray-700">Handout</th>
                    </tr>
                  </thead>
                  <tbody>
                    {game.points.map((point, index) => (
                      <tr 
                        key={index}
                        className={`
                          ${point.isHandout ? 'bg-orange-50' : 'hover:bg-gray-50'}
                          ${index % 2 === 0 ? 'bg-gray-25' : ''}
                        `}
                      >
                        <td className="border border-gray-300 px-3 py-2 text-xs text-center text-gray-900">{index + 1}</td>
                        <td className="border border-gray-300 px-3 py-2 text-xs text-center font-medium text-gray-900">{point.scorer}</td>
                        <td className="border border-gray-300 px-3 py-2 text-xs text-center text-gray-900">{point.score}</td>
                        <td className="border border-gray-300 px-3 py-2 text-xs text-center text-gray-900">{point.server}</td>
                        <td className="border border-gray-300 px-3 py-2 text-xs text-center text-gray-900">{point.servingSide}</td>
                        <td className="border border-gray-300 px-3 py-2 text-xs text-center text-gray-900">
                          {point.isHandout ? '✓' : ''}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              /* Summary View */
              <div className="space-y-4">
                <div className="grid grid-cols-auto gap-2">
                  {game.points.map((point, index) => (
                    <span
                      key={index}
                      className={`
                        inline-block px-3 py-1 rounded text-xs font-medium
                        ${point.isHandout 
                          ? 'bg-orange-100 text-orange-800' 
                          : 'bg-blue-100 text-blue-800'
                        }
                      `}
                      title={`Point ${index + 1}: ${point.scorer} scores ${point.score} (${point.server} serving ${point.servingSide}${point.isHandout ? ', handout' : ''})`}
                    >
                      {point.score}{point.isHandout ? ' (H)' : ''}
                    </span>
                  ))}
                </div>
                <div className="text-xs text-gray-500 text-center">
                  Hover over points for details • (H) = Handout • Orange = Handout, Blue = Regular scoring
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
} 